---


# ეს არის ჩვენი პირველი Ansible Playbook-ის დასაწყისი
#
# 1. PLAY: აპაჩის ინსტალაციის შემოწმება
- name: Check for existence of Apache and create a test file
  hosts: local_servers
  gather_facts: yes # გამორთვა სისწრაფისთვის
  
  tasks:
    # TASK 1: Ping (მხოლოდ იმისთვის, რომ დარწმუნდეთ, რომ კავშირი მუშაობს)
    - name: Ensure connection is successful
      ping:

    # TASK 2: File Creation (რესურსის შექმნა)
    - name: Create a simple Ansible controlled file
      ansible.builtin.file:
        path: /tmp/ansible_test.txt
        state: touch
        mode: '0644'
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
      changed_when: false 
